# Generated by Django 6.0.3 on 2026-04-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuela',
            options={'ordering': ['nombre'], 'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Opcional — si el evento tiene duración definida', null=True, verbose_name='Fecha y hora de finalización'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='facultad',
            field=models.ForeignKey(blank=True, help_text='Opcional — dejar vacío si la escuela no pertenece a una facultad separada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas', to='sistema.facultad'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateTimeField(verbose_name='Fecha y hora de inicio'),
        ),
    ]
